[package]
name = "galvanism"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["span_api"]

# Optimize for speed and reduce size on release builds
[profile.release]
codegen-units = 1
lto = true
strip = true
